spring:
  cloud:
    gateway:
      routes:
        - id: foo-route
          uri: http://localhost:2001
          predicates:
#            - Path=/foo/**,/g*/*
# 测试多个配置为与的关系
            - Path=/foo/**
            - Method=GET,POST
server:
  port: 2000